#!/bin/sh
apt update && apt upgrade -y \
&& curl -sL 'https://apt.netmaker.org/gpg.key' | tee /etc/apt/trusted.gpg.d/netclient.asc \
&& curl -sL 'https://apt.netmaker.org/debian.deb.txt' | tee /etc/apt/sources.list.d/netclient.list \
&& apt -y update \
&& apt -y install netclient
